site_name: AutoNeuro
repo_url: https://github.com/viratsagar/Autoneuro.git "target="_blank
site_url: https://Autoneuro.ml/
edit_uri: ""
site_description: 'Documentation for AutoNeuro, the automated Machine Learning Application.'

nav:
    - Home: index.html
    - About AutoNeuro:
        - Getting Started:
            - Introduction & Features : GettingStarted\GettingStarted.md
            - Installation : GettingStarted\How to use.md
        - User's Guide:
            - Uploading Data : User's Guide\Uploading Data.md
            - Data Visualization : User's Guide\Data Visualization.md
            - Model Training : User's Guide\ModelTraining.md
            - Predictions : User's Guide\Predictions.md
            - Cloud deployment : User's Guide\Clouddeployment.md
            - Logging Help : User's Guide\LoggingHelp.md
            - Troubleshooting : User's Guide\Troubleshooting.md

        - For Devlelopers :
            - Workflow: ForDevelopers\Applicationworkflow.md
            - Data upload : ForDevelopers\Methodsfordataupload.md
            - Data profiling : ForDevelopers\Methodsfordataprofiler.md
            - Data Analysis :
                - Statistical Analysis : ForDevelopers\MethodsforstatbasedEDA.md
                - Graphical Analysis : ForDevelopers\MethodsforgraphbasedEDA.md
            - Data preprocessing : ForDevelopers\Methodsforpreprocessing.md
            - Model building : ForDevelopers\MethodsforModelbuilding.md
            - Model Testing & Selection : ForDevelopers\Methodsforprediction.md
            - Deployment : ForDevelopers\Methodsfordeployment.md
            - Logging : ForDevelopers\Methodsforlogging.md
            - Methods :
                - Data Upload : ForDevelopers\Api\API_upload.md
                - Data Preprocess : ForDevelopers\Api\API_preprocess.md
                - Data Visualization : ForDevelopers\Api\visualization.md
                - Regression : ForDevelopers\Api\Regression.md
                - Classification : ForDevelopers\Api\classification.md
                - Data Logger : ForDevelopers\Api\logger.md
                - Data File : ForDevelopers\Api\file_methods.md
                - Predict : ForDevelopers\Api\API_predict.md
            
        - Contributing to autoneuro:
            - Help us improve : Contributingtoautoneuro\Contributingtoautoneuro.md
        - License : License.md
            
    - Pypi :
       - Pypi : https://pypi.org/project/pneuro/ "target="_blank
    - About us :
      - About us : https://ineuron.ai/ "target="_blank


theme:
    name: material
    custom_dir: 'docs/theme'
    palette:
        primary: Red
        accent: black

    logo: img/Ineuro.svg
    favicon: img/Ineuro.svg
    features:
      - tabs

    font:
       text: "https://fonts.googleapis.com/css2?family=Palanquin+Dark:wght@600&family=Poppins:wght@600&family=Raleway:wght@600&family=Sora:wght@700&display=swap"
       code: "https://fonts.googleapis.com/css2?family=Roboto+Mono:ital@1&display=swap"



extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/viratsagar/Autoneuro
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/futureindatascience/

    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Sudhans74624324
    - icon: fontawesome/brands/linkedin
      link: https://in.linkedin.com/organization-guest/company/ineuron-ai?challengeId=AQFdwh3-bGfX8wAAAXNrEKXH8FOn6l02HB35tFPQfdN1oUTmlkLCxriBdfiPEGtJHIy2rIBPzNQNmdvZOxTJpauHtJ-8qXepiA&submissionId=7ab9fab9-6e64-2316-15c9-b83be915c825
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/ineuron_ai/?hl=en

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - codehilite:
      guess_lang: False
      use_pygments: True
      noclasses: True
      pygments_style: monokai
  - toc:
      permalink: true
  - pymdownx.magiclink:
        repo_url_shorthand: true
        user: Nabeel
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true



google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto

plugins:
  - search:
      prebuild_index: false

extra_css:
  - css/main.css
  - stylesheets/codehilite.css

extra_javascript:
  - https://bot.dialogflow.com/823bcfe8-468c-488e-a172-0567808fb1cb
