site_name: AutoNeuro
repo_url: https://github.com/nabeelfahmi12/AutoNeuro-Documentation.git
site_url: https://Autoneuro.io/
site_description: 'Documentation for AutoNeuro, the automated Machine Learning Application.'

nav:
    - Home: index.html
    - About AutoNeuro:
        - Getting Started:
            - Introduction & Features : GettingStarted/GettingStarted.md
            - Installation : GettingStarted/How to use.md
        - User's Guide:
            - User's Guide : User's Guide/UsersGuide.md
            - Uploading Data : User's Guide/Uploading Data.md
            - Data Visualization : User's Guide/Data Visualization.md
            - Model Training : User's Guide/ModelTraining.md
            - Predictions : User's Guide/Predictions.md
            - Cloud deployment : User's Guide/Clouddeployment.md
            - Logging Help : User's Guide/LoggingHelp.md
            - Troubleshooting : User's Guide/Troubleshooting.md


        - For Devlelopers :
            - For Devlelopers : ForDevelopers\API Reference.md
            - Methods for data upload : ForDevelopers\Methodsfordataupload.md
            - Methods for preprocessing : ForDevelopers\Methodsforpreprocessing.md
            - Methods for visualization : ForDevelopers\Methodsforvisualization.md
            - Methods for Model building : ForDevelopers\MethodsforModelbuilding.md
            - Methods for prediction : ForDevelopers\Methodsforprediction.md
            - Methods for deployment : ForDevelopers\Methodsfordeployment.md
        - Application workflow : Applicationworkflow.md
        - Contributing to autoneuro:
            - Contributing to autoneuro : Contributingtoautoneuro\Contributingtoautoneuro.md
    - Pypi :
       - Pypi : "https://pypi.org/project/vowelcheck/"
    - Hardware Requirements :
      - Hardware Requirements :  "https://www.facebook.com/futureindatascience/"
    - About us :
      - About us : "https://ineuron.ai/"


theme:
    name: material
    palette:
        primary: Red
        accent: black

    logo: img/Ineuro.svg
    favicon: img/Ineuro.svg
    features:
      - tabs
    font:
       text: "https://fonts.googleapis.com/css2?family=Roboto+Mono:ital@1&display=swap"
       code: "https://fonts.googleapis.com/css2?family=Roboto+Mono:ital@1&display=swap"
    css : css/new.css



extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Jhansi-27/Sample_Auto
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/futureindatascience/
    - icon: fontawesome/brands/docker
      link: https://ineuron.ai/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Sudhans74624324
    - icon: fontawesome/brands/linkedin
      link: https://in.linkedin.com/organization-guest/company/ineuron-ai?challengeId=AQFdwh3-bGfX8wAAAXNrEKXH8FOn6l02HB35tFPQfdN1oUTmlkLCxriBdfiPEGtJHIy2rIBPzNQNmdvZOxTJpauHtJ-8qXepiA&submissionId=7ab9fab9-6e64-2316-15c9-b83be915c825
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/ineuron_ai/?hl=en

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - pymdownx.magiclink:
        repo_url_shorthand: true
        user: Nabeel
        repo: mkdocs-material
  - pymdownx.superfences
  - pymdownx.tabbed




google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto

plugins:
  - search:
      prebuild_index: false

